project:
  type: book
  output-dir: _site

book:
  title: "MASA R"
  navbar:
    pinned: true
    background: primary
    title: "MASA R"
    logo: "https://www.surrey.ac.uk/themes/custom/surrey/assets/dist/img/uos-logo.svg"
    right:
      - icon: github
        href: https://github.com/aliceccheng/masa-r
        aria-label: GitHub
  page-footer:
    left: "© 2026 University of Surrey"
    right: "Built with Quarto"
  search:
    location: sidebar
  chapters:
    - index.qmd
    - text: "Intermediate R"
      href: Intermediate_R.qmd

format:
  html:
    theme: cosmo
    toc: true